/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetofinalpoo;

import javax.swing.JLabel;

/**
 *
 * @author marcos
 */
public class TelaMensagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaMensagem
     */
    public TelaMensagem() {
        initComponents();
        setVisible(true);
    }
    
    public JLabel getAssunto() {
        return MsgAssunto;
    }
    
    public JLabel getDe() {
        return MsgDe;
    }
    
    public JLabel getPara() {
        return MsgPara;
    }
    
    public JLabel getCorpoMsg() {
        return MsgCorpo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MsgDe = new javax.swing.JLabel();
        MsgPara = new javax.swing.JLabel();
        MsgAssunto = new javax.swing.JLabel();
        MsgCorpo = new javax.swing.JLabel();

        MsgDe.setText("jLabel1");

        MsgPara.setText("jLabel2");

        MsgAssunto.setText("jLabel3");

        MsgCorpo.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MsgCorpo)
                    .addComponent(MsgAssunto)
                    .addComponent(MsgPara)
                    .addComponent(MsgDe))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(MsgDe)
                .addGap(33, 33, 33)
                .addComponent(MsgPara)
                .addGap(32, 32, 32)
                .addComponent(MsgAssunto)
                .addGap(42, 42, 42)
                .addComponent(MsgCorpo)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MsgAssunto;
    private javax.swing.JLabel MsgCorpo;
    private javax.swing.JLabel MsgDe;
    private javax.swing.JLabel MsgPara;
    // End of variables declaration//GEN-END:variables
}
